# Generated by Django 5.0.6 on 2025-03-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_game_player1_remove_game_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='rematch_player1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='rematch_player2',
            field=models.BooleanField(default=False),
        ),
    ]
